
_python_argcomplete() {
    local IFS=$''
    local SUPPRESS_SPACE=0
    if compopt +o nospace 2> /dev/null; then
        SUPPRESS_SPACE=1
    fi
    COMPREPLY=( $(IFS="$IFS"                   COMP_LINE="$COMP_LINE"                   COMP_POINT="$COMP_POINT"                   COMP_TYPE="$COMP_TYPE"                   _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS"                   _ARGCOMPLETE=1                   _ARGCOMPLETE_SUPPRESS_SPACE=$SUPPRESS_SPACE                   "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    elif [[ $SUPPRESS_SPACE == 1 ]] && [[ "$COMPREPLY" =~ [=/:]$ ]]; then
        compopt -o nospace
    fi
}
complete -o nospace -o default -o bashdefault -F _python_argcomplete "az"

[ -z "$PS1" ] && return

export PS1="\[\e[31m\]ogre\[\e[m\] \[\e[33m\]\w\[\e[m\] > "
export TERM=xterm-256color
alias grep="grep --color=auto"
alias ls="ls --color=auto"

echo -e "\e[1;36m"
cat<<'OGRE'
  ___   __ _ _ __ ___
 / _ \ / _` | '__/ _ \ 
| (_) | (_| | | |  __/
 \___/ \__, |_|  \___|
       |___/
OGRE
echo -e "\e[0;33m"

echo "
👹 Made by ogre.run, Inc. 👹 - https://ogre.run - contact@ogre.run

🌟 Star miniogre on GitHub: https://github.com/ogre-run/miniogre

✅ Like it? Subscribe to ** Ogre PRO ** to automate infrastructure for all 
of your repositories: https://app.ogre.run/auth/sign-up

🎦 Video: https://youtu.be/zOqT0UGvwJY

miniogre comes pre-installed here, but if you want it locally: 'pip install miniogre'

========================================================================================

Usage example of miniogre:

** Do 'export GOOGLE_API_KEY=<YOUR_API_KEY>' to be able to use '--provider gemini'. **
** Do 'export OPENAI_API_KEY=<YOUR_API_KEY>' to be able to use '--provider openai'. **

1. Generate reproducibility artifacts:
    'miniogre run --no-container'

2. Generate README.md:
    'miniogre readme'

"

# Turn off colors
# echo -e "\e[m"

# Aliases
alias python="python3"
# Git repo info
echo REPOSITORY = 
echo COMMIT = 
echo COMMIT_AUTHOR = 